### ISSUE TITLE
depends_on entries and vectors for hdf5 are different from publication

### ISSUE THREAD

**Issue by julianhoersch** [COMCIFS/instrument-geometry-info#45]
This is an excerpt of #42 
There are some differences between the current output of the imgCIF_creator and the published imgCIFs, which are mainly related to different naming in the hdf5 file which were manually renamed before:

```
loop_
  _axis.id
  _axis.type
  _axis.equipment
  _axis.depends_on
  _axis.vector[1]
  _axis.vector[2]
  _axis.vector[3]
  _axis.offset[1]
  _axis.offset[2]
  _axis.offset[3]
         chi       rotation  goniometer          detx      -0.0046   0.0372    -0.9993  0        0        0        
         omega     rotation  goniometer          .         1         0         0        0        0        0        
         two_theta           rotation  goniometer          .         1         0        0        0        0        0        
         phi       rotation  goniometer          chi       1         -0.0037   0.002    0        0        0        
         detx      translation         detector  dety      -1        0         0        -166.87357         172.49715          0        
         dety      translation         detector  trans     0         1         0        0        0        0        
         trans     translation         detector  omega     0         0         -1       0        0        -287.22243
```

==> chi should depend on omega
==> in the publication (he4557) _axis.equipment for two_theta was detector, not goniometer
==> trans should depend on two_theta
==> detx should depend on trans
==> dety depends on detx
==> detx vector should be [1 0 0]
==> dety vector should be [0 -1 0]

1. **chi should depend on omega**: in the h5 master it was detx, and in the imgcif_mapper I looped through the dependency chain until the base (omega) was reached. I did not do this in the creator yet, but I can implement it again.

2. **_axis.equipment for two_theta was detector, not goniometer**: I've just duplicated the omega axis and renamed it because it's the same except for the equipment type and was not present in the h5 master. I was trying to be more generic instead of hardcoding things. Is it ok to duplicate the `omega` axis, rename it to `two_theta` and replace the equipment with `detector`? 

3. In general is it correct that `two_theta` and `detector_2theta` are different axes, so the first for the goniometer and the second for the detector? Are they **always** present?

4. **trans should depend on two_theta**: I inferred the depends_on field from the `/entry/sample/transformations/sam_z` entry which depends on `omega`, previously this was manually set to two_theta. It always feels a bit arbitrary to replace things manually... I could replace it again.

5. **detx should depend on trans**: this was inferred from `/entry/sample/transformations/sam_x` which depends on `sam_y` so this also requires manual renaming

6. **dety depends on detx**: this was inferred from `/entry/sample/transformations/sam_y` which depends on `sam_z` so this also requires manual renaming

7. **detx vector should be [1 0 0]**  and **dety vector should be [0 -1 0]**: this is the same issue as mentioned in the last mail and I did not change that yet:

> You're also right with the axis vectors, that is something I wanted to discuss, but I see that I did not mention this yet... In the hdf5 file there is the /entry/instrument/detector/module/fast_pixel_direction with vector [-1,0,0] (used previously) and in /entry/sample/transformations/sam_x the vector is [1,0,0]. I was using the second one for convenience, because I thought it was the same and realized later that it's different and wanted to discuss if the first one is the correct one.

**Comment by jamesrhester** [comment]
Normally `samx` and `samy` would be sample translations to move the sample within the beam. These are axes that we would normally ignore. The detector axes would be the fast/slow pixel directions. Note that `omega` and `two_theta` are completely separate axes. The former rotates the sample and is part of the goniometer, the latter rotates the detector and is part of the detector.

**Comment by kroon-lab** [comment]
1. yes, **chi** depends on **sam_x** in h5 master. However, in a meeting with Fabio we decided to skip **sam_x,** **sam_y,****sam_z** altogether.  It is not in the core metadata list and is not used (all value zero ). 
2. Indeed, **two_theta** is not present in h5 master. In general the **two_theta** axis is parallel to the **omega** axis, so you can copy the vector and use **detector** instead of **goniometer** as the two_theta motor is supposed to rotate the detector.
3. I think there is only a **two_theta** axis for the detector, so I think **two_theta** and **detector_2theta** are the same.
4. The detector distance can be inferred from h5 master from **det_z** No dependency is given for **det_z** unfortunately. And as mentioned **two_theta** in not given in h5 master. 
5. **detx** (fast pixel direction) is not given a dependency in h5 master. But is should depend on **trans**. I think Fabio forced this.
6. **detx** and **dety** are the coordinates on the detector. They do not depend on the **sam_** definitions. We skip all the **sam** stuff anyway. **detx** is the fast pixel direction in h5 master and depends on module_offset, which depends on **det_z** which is given offset [166.874,172.49,0.0]. **det_y** is the slow pixel direction and also depends on module_offset. Since we do not use module_offset or **det_z,** we let **dety** depend on **detx** because we need the offset that is given in the **detx** data item.  @jamesrhester do you agree with this? @julianhoersch  I understand that it  is a bit inconvenient that you need to make all these decisions in the software. Is it OK with you? Fabio did this before in his imgcif_mapper.
7. detx is the correct vector to use. And it is then converted from nexus to cbf. 

The h5 master file does not completely adhere to the later HDRMX gold standard. We will definitely encounter more dialects in h5.

**Comment by jamesrhester** [comment]
I agree with Loes' descriptions.
